### ISSUE TITLE
Steps to build this tool

### ISSUE THREAD

**Issue by akshaysuryawanshi** [google/mysql-ripple#1]
This is pretty exciting tool, I wanted to start testing it, any estimates on when the steps to build it will be available as part of the README.

**Comment by codedumper1** [comment]
> This is pretty exciting tool, I wanted to start testing it, any estimates on when the steps to build it will be available as part of the README.

I made PR, instructions are here - 
https://github.com/google/mysql-ripple/pull/2/commits/1ffe1a1ff08d6ae77b6296604e26bedded8be424

**Comment by pivanof** [comment]
@dveeden I've merged #2 by @codedumper1, so I will close this issue. But please feel free to propose any additional adjustments to the README file if you think it's necessary.
