### ISSUE TITLE
On slave how to config change master

### ISSUE THREAD

**Issue by haydenxia** [google/mysql-ripple#18]
On slave,I try to issue change master to，but I do not know how to  confirm the value of master_user and master_password，the following：
change master to 
master_host='192.168.184.10',
master_user='???',
master_password='???',
master_port=15000,
master_auto_position=1;

Thanks in advance

**Comment by pivanof** [comment]
Currently by default Ripple will not do any authentication of the slave, i.e. you can provide any user and password, it will still work. There's a flag --ripple_server_password_hash. You can use it to restrict the password that slave has to use, but there's no restriction on the user yet.
