### ISSUE TITLE
missing input file

### ISSUE THREAD

**Issue by biaoyun** [google/mysql-ripple#22]
when i execute bazel build :all,i meet errors as follows

Starting local Bazel server and connecting to it...
INFO: Writing tracer profile to '/root/.cache/bazel/_bazel_root/e1a522577afd7e5ef7716dccda52fc23/command.profile.gz'
INFO: Analyzed 50 targets (43 packages loaded, 1268 targets configured).
INFO: Found 50 targets...
INFO: Deleting stale sandbox base /root/.cache/bazel/_bazel_root/e1a522577afd7e5ef7716dccda52fc23/sandbox
ERROR: missing input file '@external_libs//:mysql/byte_order_generic_x86_64.h'
ERROR: missing input file '@external_libs//:mysql/my_attribute.h'
ERROR: missing input file '@external_libs//:mysql/my_net.h'
ERROR: missing input file '@external_libs//:mysql/my_pthread.h'
ERROR: missing input file '@external_libs//:mysql/my_valgrind.h'
ERROR: missing input file '@external_libs//:mysql/private/violite.h'
ERROR: /root/.cache/bazel/_bazel_root/e1a522577afd7e5ef7716dccda52fc23/external/external_libs/BUILD.bazel:17:1: @external_libs//:mysqlclient: missing input file '@external_libs//:mysql/byte_order_generic_x86_64.h'
ERROR: /root/.cache/bazel/_bazel_root/e1a522577afd7e5ef7716dccda52fc23/external/external_libs/BUILD.bazel:17:1: @external_libs//:mysqlclient: missing input file '@external_libs//:mysql/my_attribute.h'
ERROR: /root/.cache/bazel/_bazel_root/e1a522577afd7e5ef7716dccda52fc23/external/external_libs/BUILD.bazel:17:1: @external_libs//:mysqlclient: missing input file '@external_libs//:mysql/my_net.h'
ERROR: /root/.cache/bazel/_bazel_root/e1a522577afd7e5ef7716dccda52fc23/external/external_libs/BUILD.bazel:17:1: @external_libs//:mysqlclient: missing input file '@external_libs//:mysql/my_pthread.h'
ERROR: /root/.cache/bazel/_bazel_root/e1a522577afd7e5ef7716dccda52fc23/external/external_libs/BUILD.bazel:17:1: @external_libs//:mysqlclient: missing input file '@external_libs//:mysql/my_valgrind.h'
ERROR: /root/.cache/bazel/_bazel_root/e1a522577afd7e5ef7716dccda52fc23/external/external_libs/BUILD.bazel:17:1: @external_libs//:mysqlclient: missing input file '@external_libs//:mysql/private/violite.h'
ERROR: /root/.cache/bazel/_bazel_root/e1a522577afd7e5ef7716dccda52fc23/external/external_libs/BUILD.bazel:17:1 6 input file(s) do not exist
INFO: Elapsed time: 4.358s, Critical Path: 0.04s
INFO: 0 processes.
FAILED: Build did NOT complete successfully

i can't find these file in my mysql-ripple folder,how can i get these file and add?

**Comment by pivanof** [comment]
These files are supposed to be on your machine from a MySQL client installed system-wide, and they should be located in /usr/include/mysql. On Debian/Ubuntu these files come from installation of libmariadbclient-dev package.

Sorry, I didn't make the compilation of Ripple hermetic yet. :(

**Comment by biaoyun** [comment]
my os version is ubuntu16.04,so I install libmariadbclient-dev by add some source address in /etc/apt/source.list,install successfully.But when i execute bazel build :all,I meet errors as follows

INFO: Writing tracer profile to '/root/.cache/bazel/_bazel_root/e1a522577afd7e5ef7716dccda52fc23/command.profile.gz'
INFO: Analyzed 50 targets (0 packages loaded, 0 targets configured).
INFO: Found 50 targets...
ERROR: /opt/mysql-ripple/BUILD.bazel:202:1: undeclared inclusion(s) in rule '//:base':
this rule is missing dependency declarations for the following files included by 'flags.cc':
  '/usr/lib/gcc/x86_64-linux-gnu/7/include/stddef.h'
  '/usr/lib/gcc/x86_64-linux-gnu/7/include/stdarg.h'
  '/usr/lib/gcc/x86_64-linux-gnu/7/include/stdint.h'
INFO: Elapsed time: 0.519s, Critical Path: 0.36s
INFO: 0 processes.
FAILED: Build did NOT complete successfully

How to declare these file in rule '//:base'?Ripple Whether can compilation in ubuntu16.04?
